export class StripeConfigurationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "StripeConfigurationError";
  }
}

export class StripeServerUnavailableError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "StripeServerUnavailableError";
  }
}

export const STRIPE_CHECKOUT_ERROR_CODES = {
  INVALID_CHECKOUT_REQUEST: "INVALID_CHECKOUT_REQUEST",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  PRODUCT_NOT_PURCHASABLE: "PRODUCT_NOT_PURCHASABLE",
  ALREADY_ENROLLED: "ALREADY_ENROLLED",
  STRIPE_NOT_CONFIGURED: "STRIPE_NOT_CONFIGURED",
  CHECKOUT_CREATION_FAILED: "CHECKOUT_CREATION_FAILED",
  PURCHASE_CREATION_FAILED: "PURCHASE_CREATION_FAILED",
  PURCHASE_EVENT_CREATION_FAILED: "PURCHASE_EVENT_CREATION_FAILED",
  CHECKOUT_SESSION_ATTACH_FAILED: "CHECKOUT_SESSION_ATTACH_FAILED",
  CHECKOUT_SESSION_EXPIRATION_FAILED: "CHECKOUT_SESSION_EXPIRATION_FAILED",
  DUPLICATE_PENDING_PURCHASE: "DUPLICATE_PENDING_PURCHASE",
  PRICE_NOT_PURCHASABLE: "PRICE_NOT_PURCHASABLE",
  PRICE_AMOUNT_UNAVAILABLE: "PRICE_AMOUNT_UNAVAILABLE",
  PURCHASE_METADATA_MISMATCH: "PURCHASE_METADATA_MISMATCH",
  PAYMENT_INTENT_MISMATCH: "PAYMENT_INTENT_MISMATCH",
  CHECKOUT_AMOUNT_MISMATCH: "CHECKOUT_AMOUNT_MISMATCH",
  CHECKOUT_CURRENCY_MISMATCH: "CHECKOUT_CURRENCY_MISMATCH",
  CHECKOUT_REFERENCE_MISMATCH: "CHECKOUT_REFERENCE_MISMATCH",
  CHECKOUT_PRODUCT_MISMATCH: "CHECKOUT_PRODUCT_MISMATCH",
  CHECKOUT_PROFILE_MISMATCH: "CHECKOUT_PROFILE_MISMATCH",
  PAYMENT_AMOUNT_MISMATCH: "PAYMENT_AMOUNT_MISMATCH",
  PAYMENT_CURRENCY_MISMATCH: "PAYMENT_CURRENCY_MISMATCH",
  PAYMENT_METADATA_MISMATCH: "PAYMENT_METADATA_MISMATCH",
  PAYMENT_STATUS_INVALID: "PAYMENT_STATUS_INVALID",
  PURCHASE_STATE_TRANSITION_INVALID: "PURCHASE_STATE_TRANSITION_INVALID",
  DATABASE_UNAVAILABLE: "DATABASE_UNAVAILABLE",
  WEBHOOK_EVENT_WRITE_FAILED: "WEBHOOK_EVENT_WRITE_FAILED",
  PURCHASE_UPDATE_FAILED: "PURCHASE_UPDATE_FAILED",
  STRIPE_API_TEMPORARY_FAILURE: "STRIPE_API_TEMPORARY_FAILURE",
  PURCHASE_AMOUNT_INVALID: "PURCHASE_AMOUNT_INVALID",
} as const;

export type StripeCheckoutErrorCode =
  (typeof STRIPE_CHECKOUT_ERROR_CODES)[keyof typeof STRIPE_CHECKOUT_ERROR_CODES];

export class StripeCheckoutError extends Error {
  readonly code: StripeCheckoutErrorCode;
  readonly status: number;
  override readonly cause?: unknown;

  constructor(
    code: StripeCheckoutErrorCode,
    message: string,
    options?: {
      status?: number;
      cause?: unknown;
    },
  ) {
    super(message);
    this.name = "StripeCheckoutError";
    this.code = code;
    this.status = options?.status ?? 500;
    this.cause = options?.cause;
  }
}
